apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: katka-tekton
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/kkanova0/node:9bc02dc577643f60eda34bdcbfa73490945106de@sha256:0c65e0c48ae661391bb9e2fcd09f69dd4422ad5d794b69b5cab552ec1b05792a
          name: container-image
