apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: katka-tekton
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: katka-tekton 
  name: katka-tekton
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: katka-tekton 
